FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
ARG GITVERSION
WORKDIR /app
ARG GITVERSION

# Copy csproj and restore as distinct layers
COPY eform-debian-service ./eform-debian-service
RUN dotnet publish -o out /p:Version=$GITVERSION --runtime linux-x64 --configuration Release eform-debian-service
RUN pwd
RUN ls -lah out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "MicrotingService.dll"]
